export const SET_USER_TOKEN = 'SET_USER_TOKEN'

export const SET_FIRST_LOGIN = 'SET_FIRST_LOGIN'

export const SET_USER_ID = 'SET_USER_ID'

export const SET_DETAIL = 'SET_DETAIL'

export const TOGGLE_DETAIL_PAGE = 'TOGGLE_DETAIL_PAGE'

export const SET_DISCOVERY_ITEM = 'SET_DISCOVERY_ITEM'

export const SET_DYNAMIC_ITEM = 'SET_DYNAMIC_ITEM'

export const SET_VISITED_LIST = 'SET_VISITED_LIST'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_ANALYSIS_ITEM = 'SET_ANALYSIS_ITEM'
